include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - avoid_empty_else
    - avoid_escaping_inner_quotes
    - avoid_null_checks_in_equality_operators
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_setters_without_getters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - prefer_double_quotes
